module.exports = {
    _8ball: require('./8ball'),
    avatar: require('./avatar'),
    gamblping: require('./gamblping'),
    choose: require('./choose'),
    convert: require('./convert'),
    dev: require('./dev'),
    eval: require('./eval'),
    git: require('./git'),
    jumbo: require('./jumbo'),
    ping: require('./ping'),
    redpanda: require('./redpanda'),
    remind: require('./remind'),
    restart: require('./restart'),
    role: require('./role'),
    roll: require('./roll'),
    server: require('./server'),
    shutdown: require('./shutdown'),
    terminal: require('./terminal'),
    update: require('./update'),
    user: require('./user')
};
