module.exports = [
    require('./8ball'),
    require('./avatar'),
    require('./banner'),
    require('./birthday'),
    // require('./blackjack'),
    require('./choose'),
    require('./convert'),
    require('./emoji'),
    require('./eval'),
    require('./flip'),
    require('./ping'),
    require('./pipe'),
    require('./qotd'),
    require('./remind'),
    require('./roll'),
    // require('./server'),
    require('./terminal'),
    // require('./user')
];
